apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.7.12
    helm:
      valuesObject:
        auth:
          username: mmuser
          database: mattermost
          existingSecret: postgres-credentials
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
        primary:
          persistence:
            size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true