apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      valuesObject:
        mode: standalone
        replicas: 1
        auth:
          existingSecret: minio
        defaultBuckets: mattermost
        persistence:
          size: 1Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: minio
      namespace: mattermost
      jsonPointers:
        - /data